### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/infografia-Rosa218#1]
![Ingenieria de (1)](https://user-images.githubusercontent.com/72048522/153823328-2aade206-1b07-4bb3-9b87-a14a14601603.png)

**Comment by bg55-a** [comment]
Calificación 20
Calificó: Adolfo Germán Vasquez Rojas

**Comment by josealfredo79** [comment]
Bien hecho y revisado
